name: Elixir CI

permissions:
  contents: read
  pull-requests: write
  checks: write

on:
  push:
    branches:
      - main
  pull_request:

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          elixir-version: 1.15

      - name: Install Mix Dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

      - name: Run Tests
        run: mix lcov

      - name: Coverage
        uses: peek-travel/coverage-reporter@main
        if: github.event_name == 'pull_request'
        with:
          pull_number: ${{ github.event.number }}
          repository: ${{ github.repository }}
          head_branch: ${{ github.head_ref }}
          lcov_path: cover/lcov.info
          coverage_threshold: 90

      - name: Run dialyzer
        run: MIX_ENV=dev mix dialyzer --format github
